### ISSUE TITLE
CMake Warning in `tut/000/CMakeLists.txt` - `cmake_minimum_required` should be called

### ISSUE THREAD

**Issue by VincentRouvreau** [0xz/cmake_survival#3]
I do not know how you want to introduce the different concepts of CMake, but `cmake_minimum_required` is advised (cf. [CMake tutorial](https://cmake.org/cmake/help/latest/guide/tutorial/A%20Basic%20Starting%20Point.html#exercise-1-building-a-basic-project))
```bash
tut/000/run.sh
CMake Warning (dev) at CMakeLists.txt:2 (project):
  cmake_minimum_required() should be called prior to this top-level project()
  call.  Please see the cmake-commands(7) manual for usage documentation of
  both commands.
This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Comment by PhilipDeegan** [comment]
not sure I want to complicate the very first tutorial, but perhaps `cmake_minimum_required(3.0)` will suffice
