### ISSUE TITLE
Ninja should not be used before to be introduced

### ISSUE THREAD

**Issue by VincentRouvreau** [0xz/cmake_survival#4]
It seems to me you want to introduce ninja in `tut/006`. This is why ninja should not be used before and specifically in `tut/002`:
https://github.com/0xz/cmake_survival/blob/4e9f687bf9ec543d2675a0fa9dfc7fa8c9a13553/tut/002/run.sh#L5

**Comment by PhilipDeegan** [comment]
right, we can show the other method directly from cmake here perhaps, e.g. `cmake --build ...`

**Comment by PhilipDeegan** [comment]
closed by #6
