### ISSUE TITLE
I would not advise to `set(CMAKE_BUILD_TYPE "Debug/Release")`

### ISSUE THREAD

**Issue by VincentRouvreau** [0xz/cmake_survival#5]
To be discussed, and you can close it if you find it irrelevant, but I would not advise (cf. `tut/004` and `tut/005`) to `set(CMAKE_BUILD_TYPE "Debug/Release")` in CMakeLists.txt.

I would show how to use it in command line with `cmake -DCMAKE_BUILD_TYPE "Debug/Release" ..`

**Comment by PhilipDeegan** [comment]
sure, also we can do something if it's not set from command line, with a default

**Comment by PhilipDeegan** [comment]
closed by #6
